# Generated by Django 5.2.4 on 2025-07-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('nin', models.CharField(max_length=20, unique=True)),
                ('recommender', models.CharField(max_length=100)),
                ('recommender_nin', models.CharField(max_length=20, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('farmer_type', models.CharField(choices=[('starter', 'Starter'), ('returning', 'Returning')], default='starter', max_length=10)),
            ],
        ),
    ]
