# Generated by Django 5.2.4 on 2025-07-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='recommender_nin',
            field=models.CharField(max_length=20),
        ),
    ]
