# Generated by Django 5.2.4 on 2025-08-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_chickrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='chickrequest',
            name='is_picked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chickrequest',
            name='picked_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chickrequest',
            name='pickup_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
