# Generated by Django 5.2.4 on 2025-08-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_feedrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='contact',
            new_name='contact_person',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
