# Generated by Django 5.2.4 on 2025-08-17 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_rename_contact_manufacturer_contact_person_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chickrequest',
            name='decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chickrequest',
            name='decision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_chick_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chickrequest',
            name='decision_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
