# Generated by Django 5.2.4 on 2025-07-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChickStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chick_type', models.CharField(choices=[('layer_local', 'Layer - Local'), ('layer_exotic', 'Layer - Exotic'), ('broiler_local', 'Broiler - Local'), ('broiler_exotic', 'Broiler - Exotic')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('age_days', models.PositiveIntegerField(help_text='Age of chicks in days')),
                ('recorded_on', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
