# Generated by Django 5.2.4 on 2025-08-16 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
        ('sales', '0007_rename_contact_manufacturer_contact_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChickAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('allocated_on', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='sales.chickrequest')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='manager.chickstock')),
            ],
        ),
    ]
